//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToList
    {
        public string UserId { get; set; }
        public int ListId { get; set; }
        public int UserToListId { get; set; }
    
        public virtual ProductList ProductList { get; set; }
    }
}
